#INIT PLUTUS ENVS ~/.bashrc - DONT DELETE THIS LINE 

CARDANO_NODE_NETWORK="MAINNET"
export CARDANO_NODE_NETWORK


source "$FALCON_DEVS_SCRIPTS/tools/write-env-list.sh"


#END PLUTUS ENVS ~/.bashrc - DONT DELETE THIS LINE
